name: Update Image Index

on:
  push:
    paths:
      - "images/**"
      - "!images/index.json"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow

      - name: Update index.json
        run: python scripts/update_index.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images/index.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update index.json"
            git push
          fi